#############################################################################
#                                                                           #
#    S E R V E R       MOTHER HOME TECH                 RUN ON SOL 1.0.0    #
#                                                                           #
#############################################################################

# This code will be for the most part auto generated by the anvil app ui
# The functions under "C A L L - T H E S E" will tell the PICO W what do and when

import plotly.graph_objects as go
import anvil.server
import anvil.tables as tables
import anvil.tables.query as q
from anvil.tables import app_tables

class Form1(Form1Template):
  def __init__(self, **properties):
    # Set Form properties and Data Bindings.
    self.init_components(**properties)

    # Any code you write here will run when the form opens.
    # x, y = anvil.server.call('tankData')
    # self.plot_1.data = go.Scatter(x=x, y=y, mode='lines')

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - C A L L - T H E S E

  def notify_click(self, **event_args):
    """This method is called when the button is clicked"""
    anvil.server.call('notify')

  def sing_click(self, **event_args):
    """This method is called when the button is clicked"""
    anvil.server.call('soundOne')

  def autoWater_tick(self, **event_args):
    """This method is called Every [interval] seconds. Does not trigger if [interval] is 0."""
    anvil.server.call('waterAuto')
